version: '2'
services:
  mtail:
    build: mtail
    command:
      - "-progs"
      - "/etc/mtail"
      - "-logs"
      - "/var/log/chia/debug.log"
      - "-logtostderr"
    volumes:
      - /var/lib/docker/volumes/chia/_data/log/:/var/log/chia/
      #- ${HOME}/.chia/mainnet/log/:/var/log/chia/
    network_mode: host
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    command:
      - '--path.rootfs=/host'
    pid: host
    volumes:
      - '/:/host:ro,rslave'
    network_mode: host
  chia_exporter:
    build: chia_exporter
    command:
      - "-cert"
      - "/etc/chia.crt"
      - "-key"
      - "/etc/chia.key"
    volumes:
      - /var/lib/docker/volumes/chia/_data/config/ssl/full_node/private_full_node.crt:/etc/chia.crt
      - /var/lib/docker/volumes/chia/_data/config/ssl/full_node/private_full_node.key:/etc/chia.key
      #- ${HOME}/.chia/mainnet/config/ssl/full_node/private_full_node.crt:/etc/chia.crt
      #- ${HOME}/.chia/mainnet/config/ssl/full_node/private_full_node.key:/etc/chia.key
      - /home/andre/Desktop/chia/all_plots/1_nft/Plot_NFT_1/:/home/andre/Desktop/chia/all_plots/1_nft/Plot_NFT_1/
      - /home/andre/Desktop/chia/all_plots/2_nft/:/home/andre/Desktop/chia/all_plots/2_nft/
      - /home/andre/Desktop/chia/all_plots/3_mix/Plot_NFT_3/:/home/andre/Desktop/chia/all_plots/3_mix/Plot_NFT_3/
      #- /home/andre/Desktop/chia/all_plots/3_mix/Plot\ remote\ 3/:/home/andre/Desktop/chia/all_plots/3_mix/Plot\ remote\ 3/
      - /home/andre/Desktop/chia/all_plots/4_nft/NFT/:/home/andre/Desktop/chia/all_plots/4_nft/NFT/
    network_mode: host
  prometheus:
    build: prometheus
    volumes:
      - prom_data:/prometheus
    network_mode: host
  loki:
    image: grafana/loki:2.0.0
    command: -config.file=/etc/loki/local-config.yaml
    network_mode: host
  promtail:
    build: promtail
    volumes:
      - /var/lib/docker/volumes/chia/_data/log/:/var/log/chia/
      #- ${HOME}/.chia/mainnet/log:/var/log/chia
      #- ${HOME}/.chia/mainnet/plotter:/var/log/plotter
    command: -config.file=/etc/promtail/config.yml
    network_mode: host
  grafana:
    build: grafana
    network_mode: host
    ports:
      - "6666:6666"
    volumes:
      - grafana:/etc/grafana
volumes:
  prom_data:
  grafana:
